import type { VaultComponent } from "@/types/vault";

const sharedTokens = [
  { id: "base-ui-accent", type: "color" as const, name: "accent.primary", value: "#6366F1" },
  { id: "base-ui-radius", type: "radius" as const, name: "radius.control", value: "12px" },
  { id: "base-ui-shadow", type: "shadow" as const, name: "shadow.panel", value: "0 18px 60px rgba(23,26,43,.08)" },
];

const usage = [{ id: "usage-reference", projectName: "Base UI reference", location: "Reference catalog", url: "https://github.com/mui/base-ui", count: 1 }];

type Reference = {
  slug: string;
  name: string;
  category: VaultComponent["category"];
  description: string;
  tags: string[];
  previewLabel: string;
  previewHtml: string;
  usageCode: string;
};

const references: Reference[] = [
  { slug: "base-ui-accordion", name: "Base UI / Accordion", category: "Surfaces", description: "Disclosure pattern for progressively revealing related content with keyboard-friendly interaction.", tags: ["base-ui", "accordion", "disclosure", "accessibility"], previewLabel: "Accordion", previewHtml: '<div class="base-ui-ref"><strong>Shipping details</strong><span>+</span></div><div class="base-ui-ref open"><strong>Returns</strong><span>−</span><small>30-day return policy.</small></div>', usageCode: `<Accordion><Accordion.Item>...</Accordion.Item></Accordion>` },
  { slug: "base-ui-alert-dialog", name: "Base UI / Alert Dialog", category: "Feedback", description: "Modal confirmation pattern for actions that need explicit user attention.", tags: ["base-ui", "dialog", "confirmation", "accessibility"], previewLabel: "Alert Dialog", previewHtml: '<div class="base-ui-dialog"><small>Confirm action</small><strong>Delete component?</strong><span>This action cannot be undone.</span><div><button>Cancel</button><button class="accent">Delete</button></div></div>', usageCode: `<AlertDialog.Root><AlertDialog.Trigger>Delete</AlertDialog.Trigger>...</AlertDialog.Root>` },
  { slug: "base-ui-autocomplete", name: "Base UI / Autocomplete", category: "Forms", description: "Text input with filtered suggestions and a keyboard-driven selection model.", tags: ["base-ui", "autocomplete", "input", "keyboard"], previewLabel: "Autocomplete", previewHtml: '<div class="base-ui-field"><label>Component</label><strong>but</strong><div class="base-ui-menu"><span>Button</span><span>Button Group</span></div></div>', usageCode: `<Autocomplete.Root items={components}><Autocomplete.Input />...</Autocomplete.Root>` },
  { slug: "base-ui-checkbox", name: "Base UI / Checkbox", category: "Forms", description: "Controlled boolean field with explicit checked and indeterminate states.", tags: ["base-ui", "checkbox", "form", "a11y"], previewLabel: "Checkbox", previewHtml: '<div class="base-ui-row"><span class="base-ui-checkbox checked">✓</span><strong>Use system tokens</strong></div><div class="base-ui-row"><span class="base-ui-checkbox"> </span><span>Show legacy usage</span></div>', usageCode: `<Checkbox.Root checked={checked} onCheckedChange={setChecked} />` },
  { slug: "base-ui-collapsible", name: "Base UI / Collapsible", category: "Surfaces", description: "Compact disclosure control for optional content in dense interfaces.", tags: ["base-ui", "collapsible", "disclosure"], previewLabel: "Collapsible", previewHtml: '<div class="base-ui-row"><strong>Advanced settings</strong><span>⌄</span></div><div class="base-ui-note">Semantic coverage · 92%</div>', usageCode: `<Collapsible.Root><Collapsible.Trigger>Advanced settings</Collapsible.Trigger>...</Collapsible.Root>` },
  { slug: "base-ui-combobox", name: "Base UI / Combobox", category: "Forms", description: "Searchable selection control combining an input, list and active option state.", tags: ["base-ui", "combobox", "select", "search"], previewLabel: "Combobox", previewHtml: '<div class="base-ui-field"><label>Framework</label><strong>React</strong><span>⌄</span></div><div class="base-ui-menu"><span class="selected">React</span><span>Vue</span><span>Svelte</span></div>', usageCode: `<Combobox.Root items={frameworks}><Combobox.Input /><Combobox.List />...</Combobox.Root>` },
  { slug: "base-ui-context-menu", name: "Base UI / Context Menu", category: "Navigation", description: "Pointer and keyboard context actions anchored to a target surface.", tags: ["base-ui", "context-menu", "menu", "keyboard"], previewLabel: "Context Menu", previewHtml: '<div class="base-ui-menu context"><span>Copy</span><span>Duplicate</span><span>Inspect</span><span>Delete</span></div>', usageCode: `<ContextMenu.Root><ContextMenu.Trigger>...</ContextMenu.Trigger><ContextMenu.Popup>...</ContextMenu.Popup></ContextMenu.Root>` },
  { slug: "base-ui-dialog", name: "Base UI / Dialog", category: "Surfaces", description: "Modal surface with focus management and composable header, body and actions.", tags: ["base-ui", "dialog", "modal", "focus"], previewLabel: "Dialog", previewHtml: '<div class="base-ui-dialog"><small>Edit component</small><strong>Feature Spotlight Card</strong><span>Update metadata, tokens and usage.</span><div><button>Cancel</button><button class="accent">Save</button></div></div>', usageCode: `<Dialog.Root><Dialog.Trigger>Edit</Dialog.Trigger><Dialog.Portal>...</Dialog.Portal></Dialog.Root>` },
  { slug: "base-ui-field", name: "Base UI / Field", category: "Forms", description: "Form field composition for labels, controls, descriptions and validation messaging.", tags: ["base-ui", "field", "form", "validation"], previewLabel: "Field", previewHtml: '<div class="base-ui-field"><label>Component name</label><input value="Spotlight Card" readonly /><small>Choose a stable public name.</small></div>', usageCode: `<Field.Root><Field.Label>Name</Field.Label><Field.Control /><Field.Description>...</Field.Description></Field.Root>` },
  { slug: "base-ui-menu", name: "Base UI / Menu", category: "Navigation", description: "Composable menu with items, groups, separators and nested interactions.", tags: ["base-ui", "menu", "navigation", "keyboard"], previewLabel: "Menu", previewHtml: '<div class="base-ui-menu"><span>Open</span><span>Duplicate</span><span>Move to collection</span><hr /><span>Delete</span></div>', usageCode: `<Menu.Root><Menu.Trigger>Actions</Menu.Trigger><Menu.Portal><Menu.Popup>...</Menu.Popup></Menu.Portal></Menu.Root>` },
  { slug: "base-ui-menubar", name: "Base UI / Menubar", category: "Navigation", description: "Application-style menu bar for grouped commands and keyboard navigation.", tags: ["base-ui", "menubar", "navigation", "commands"], previewLabel: "Menubar", previewHtml: '<div class="base-ui-menubar"><span>File</span><span>Edit</span><span>View</span><span>Help</span></div>', usageCode: `<Menubar.Root><Menubar.Menu><Menubar.Trigger>File</Menubar.Trigger>...</Menubar.Menu></Menubar.Root>` },
  { slug: "base-ui-navigation-menu", name: "Base UI / Navigation Menu", category: "Navigation", description: "Navigation surface for grouped destinations with accessible popup behavior.", tags: ["base-ui", "navigation", "menu", "responsive"], previewLabel: "Navigation Menu", previewHtml: '<div class="base-ui-nav"><strong>Components</strong><span>Patterns</span><span>Guides</span><span>Reference</span></div>', usageCode: `<NavigationMenu.Root><NavigationMenu.List>...</NavigationMenu.List></NavigationMenu.Root>` },
  { slug: "base-ui-number-field", name: "Base UI / Number Field", category: "Forms", description: "Numeric input with increment, decrement and validation affordances.", tags: ["base-ui", "number-field", "input", "forms"], previewLabel: "Number Field", previewHtml: '<div class="base-ui-field"><label>Columns</label><div class="base-ui-stepper"><button>−</button><strong>4</strong><button>+</button></div></div>', usageCode: `<NumberField.Root defaultValue={4}><NumberField.Group>...</NumberField.Group></NumberField.Root>` },
  { slug: "base-ui-popover", name: "Base UI / Popover", category: "Surfaces", description: "Anchored floating content for controls, filters and contextual details.", tags: ["base-ui", "popover", "overlay", "anchor"], previewLabel: "Popover", previewHtml: '<div class="base-ui-popover"><small>Component health</small><strong>96% governed</strong><span>4 legacy findings remain.</span></div>', usageCode: `<Popover.Root><Popover.Trigger>Health</Popover.Trigger><Popover.Portal><Popover.Popup>...</Popover.Popup></Popover.Portal></Popover.Root>` },
  { slug: "base-ui-progress", name: "Base UI / Progress", category: "Feedback", description: "Progress indicator for determinate or ongoing work.", tags: ["base-ui", "progress", "status"], previewLabel: "Progress", previewHtml: '<div class="base-ui-progress"><span style="width:72%"></span></div><small>72% analyzed</small>', usageCode: `<Progress.Root value={72}><Progress.Track><Progress.Indicator /></Progress.Track></Progress.Root>` },
  { slug: "base-ui-radio-group", name: "Base UI / Radio Group", category: "Forms", description: "Single-choice field for mutually exclusive configuration options.", tags: ["base-ui", "radio", "form", "selection"], previewLabel: "Radio Group", previewHtml: '<div class="base-ui-radio selected">● <strong>Semantic governance</strong></div><div class="base-ui-radio">○ <span>Legacy mode</span></div>', usageCode: `<RadioGroup.Root value={mode} onValueChange={setMode}>...</RadioGroup.Root>` },
  { slug: "base-ui-scroll-area", name: "Base UI / Scroll Area", category: "Utilities", description: "Contained scrolling region for dense content without breaking page flow.", tags: ["base-ui", "scroll-area", "overflow"], previewLabel: "Scroll Area", previewHtml: '<div class="base-ui-scroll"><span>Component API</span><span>Tokens</span><span>Usage</span><span>Notes</span><span>Governance</span></div>', usageCode: `<ScrollArea.Root><ScrollArea.Viewport>...</ScrollArea.Viewport><ScrollArea.Scrollbar /></ScrollArea.Root>` },
  { slug: "base-ui-select", name: "Base UI / Select", category: "Forms", description: "Accessible select control for choosing one value from a collection.", tags: ["base-ui", "select", "form", "keyboard"], previewLabel: "Select", previewHtml: '<div class="base-ui-field"><label>View mode</label><div class="base-ui-select"><strong>Grid</strong><span>⌄</span></div></div>', usageCode: `<Select.Root value={view} onValueChange={setView}><Select.Trigger>...</Select.Trigger><Select.Popup>...</Select.Popup></Select.Root>` },
  { slug: "base-ui-slider", name: "Base UI / Slider", category: "Forms", description: "Single or multi-thumb range control for continuous values.", tags: ["base-ui", "slider", "range", "input"], previewLabel: "Slider", previewHtml: '<div class="base-ui-slider"><span style="width:64%"></span><i style="left:64%"></i></div><small>Zoom · 64%</small>', usageCode: `<Slider.Root value={[64]} onValueChange={setZoom}><Slider.Control>...</Slider.Control></Slider.Root>` },
  { slug: "base-ui-switch", name: "Base UI / Switch", category: "Forms", description: "Binary setting control with explicit on and off states.", tags: ["base-ui", "switch", "settings", "a11y"], previewLabel: "Switch", previewHtml: '<div class="base-ui-row"><strong>Strict governance</strong><span class="base-ui-switch on"><i></i></span></div>', usageCode: `<Switch.Root checked={strict} onCheckedChange={setStrict}><Switch.Thumb /></Switch.Root>` },
  { slug: "base-ui-tabs", name: "Base UI / Tabs", category: "Navigation", description: "Tablist pattern for switching between related views while preserving context.", tags: ["base-ui", "tabs", "navigation", "keyboard"], previewLabel: "Tabs", previewHtml: '<div class="base-ui-tabs"><span class="active">Code</span><span>Preview</span><span>Usage</span></div><div class="base-ui-tab-panel">Component.tsx</div>', usageCode: `<Tabs.Root defaultValue="code"><Tabs.List>...</Tabs.List><Tabs.Panel value="code">...</Tabs.Panel></Tabs.Root>` },
  { slug: "base-ui-toggle", name: "Base UI / Toggle", category: "Forms", description: "Pressed-state control for reversible formatting or mode switches.", tags: ["base-ui", "toggle", "pressed", "toolbar"], previewLabel: "Toggle", previewHtml: '<div class="base-ui-toggle-group"><button class="active">B</button><button>I</button><button>U</button></div>', usageCode: `<Toggle.Root pressed={bold} onPressedChange={setBold}>Bold</Toggle.Root>` },
  { slug: "base-ui-toggle-group", name: "Base UI / Toggle Group", category: "Forms", description: "Grouped toggle controls supporting single or multiple selected values.", tags: ["base-ui", "toggle-group", "selection", "toolbar"], previewLabel: "Toggle Group", previewHtml: '<div class="base-ui-toggle-group"><button class="active">Grid</button><button>List</button><button>Split</button></div>', usageCode: `<ToggleGroup.Root value={[mode]} onValueChange={setMode}>...</ToggleGroup.Root>` },
  { slug: "base-ui-toolbar", name: "Base UI / Toolbar", category: "Navigation", description: "Keyboard-aware action grouping for compact editor and productivity controls.", tags: ["base-ui", "toolbar", "keyboard", "actions"], previewLabel: "Toolbar", previewHtml: '<div class="base-ui-toolbar"><button>Undo</button><button>Redo</button><span></span><button class="accent">Preview</button></div>', usageCode: `<Toolbar.Root><Toolbar.Button>Undo</Toolbar.Button><Toolbar.Button>Redo</Toolbar.Button>...</Toolbar.Root>` },
  { slug: "base-ui-tooltip", name: "Base UI / Tooltip", category: "Feedback", description: "Contextual description for controls that need a concise explanation.", tags: ["base-ui", "tooltip", "hover", "keyboard"], previewLabel: "Tooltip", previewHtml: '<div class="base-ui-tooltip-demo"><button>?</button><span>Governance coverage</span></div>', usageCode: `<Tooltip.Root><Tooltip.Trigger>?</Tooltip.Trigger><Tooltip.Portal><Tooltip.Popup>...</Tooltip.Popup></Tooltip.Portal></Tooltip.Root>` },
  { slug: "base-ui-toast", name: "Base UI / Toast", category: "Feedback", description: "Transient status message for save, sync and workflow feedback.", tags: ["base-ui", "toast", "notification", "status"], previewLabel: "Toast", previewHtml: '<div class="base-ui-toast"><strong>Saved</strong><span>Component updated successfully.</span><button>×</button></div>', usageCode: `<Toast.Provider><Toast.Root><Toast.Title>Saved</Toast.Title><Toast.Description>...</Toast.Description></Toast.Root></Toast.Provider>` },
  { slug: "base-ui-preview-card", name: "Base UI / Preview Card", category: "Surfaces", description: "Anchored preview surface for richer link and content previews.", tags: ["base-ui", "preview-card", "popover", "content"], previewLabel: "Preview Card", previewHtml: '<div class="base-ui-preview"><small>Component</small><strong>Button / Primary</strong><span>Accessible action control with semantic variants.</span></div>', usageCode: `<PreviewCard.Root><PreviewCard.Trigger>Button</PreviewCard.Trigger><PreviewCard.Portal><PreviewCard.Popup>...</PreviewCard.Popup></PreviewCard.Portal></PreviewCard.Root>` },
];

export const baseUiReferenceComponents: VaultComponent[] = references.map((reference, index) => ({
  id: reference.slug,
  name: reference.name,
  slug: reference.slug,
  description: reference.description,
  category: reference.category,
  framework: "React",
  language: "tsx",
  version: `Base UI · reference ${index + 1}`,
  isFavorite: false,
  isPublic: true,
  updatedAt: "2026-08-14T10:00:00.000Z",
  userId: "base-ui-reference",
  tags: reference.tags,
  previewHtml: reference.previewHtml,
  code: `// Reference inspired by Base UI's unstyled component model.\n// Adapt the composition to your own design-system contract.\n\n${reference.usageCode}`,
  styles: `.base-ui-ref { display:flex; align-items:center; justify-content:space-between; gap:12px; padding:14px 16px; border:1px solid #E4E7EF; border-radius:14px; background:#fff; color:#171A2B; }\n.base-ui-ref + .base-ui-ref { margin-top:8px; }\n.base-ui-dialog, .base-ui-popover, .base-ui-preview, .base-ui-toast, .base-ui-menu, .base-ui-field, .base-ui-toolbar, .base-ui-nav, .base-ui-tabs, .base-ui-menubar { border:1px solid #E4E7EF; border-radius:18px; background:#fff; box-shadow:0 18px 48px rgba(23,26,43,.08); }`,
  usageCode: reference.usageCode,
  notes: `Reference pattern inspired by the public Base UI project. This is an original Component Vault implementation prompt, not a copied implementation. Source: https://github.com/mui/base-ui`,
  tokens: sharedTokens,
  usage,
  props: { variant: "Reference", size: "Medium", state: "Default", iconLeft: false, iconRight: false, fullWidth: false, disabled: false, loading: false },
  collectionIds: ["base-ui-references"],
}));
