import type { VaultComponent } from "@/types/vault";

type CatalogComponent = { id: string; name: string; category: VaultComponent["category"]; description: string; tags: string[] };

const catalog: CatalogComponent[] = [
  { id: "shadcn-dialog", name: "Dialog / Composable", category: "Surfaces", description: "Composable modal pattern with explicit parts, keyboard behavior and controlled state.", tags: ["dialog", "composition", "a11y"] },
  { id: "shadcn-command", name: "Command / Palette", category: "Navigation", description: "Keyboard-first command surface for search, navigation and actions.", tags: ["command", "keyboard", "search"] },
  { id: "shadcn-sidebar", name: "Sidebar / Application Shell", category: "Navigation", description: "Collapsible application sidebar pattern with grouped navigation and responsive behavior.", tags: ["sidebar", "navigation", "app-shell"] },
  { id: "shadcn-data-table", name: "Data Table / Composable", category: "Data Display", description: "Composable table pattern for sorting, filtering, selection and pagination.", tags: ["table", "data", "composition"] },
  { id: "shadcn-sheet", name: "Sheet / Side Panel", category: "Surfaces", description: "Responsive side panel pattern for secondary workflows and inspectors.", tags: ["sheet", "drawer", "responsive"] },
  { id: "radix-popover", name: "Popover / Primitive", category: "Surfaces", description: "Anchored overlay primitive with focus management and collision-aware positioning.", tags: ["popover", "overlay", "a11y"] },
  { id: "radix-tooltip", name: "Tooltip / Accessible", category: "Feedback", description: "Accessible contextual hint with trigger, delay and keyboard semantics.", tags: ["tooltip", "a11y", "interaction"] },
  { id: "radix-dropdown", name: "Dropdown / Menu", category: "Navigation", description: "Keyboard-accessible action menu with roving focus and nested options.", tags: ["menu", "keyboard", "a11y"] },
  { id: "storybook-controls", name: "Controls / Component Playground", category: "Utilities", description: "Interactive control surface for changing component props and viewing states.", tags: ["controls", "props", "testing"] },
  { id: "storybook-states", name: "States / Visual Review", category: "Data Display", description: "Structured preview of component states for review and regression checks.", tags: ["states", "visual", "testing"] },
  { id: "storybook-interactions", name: "Interactions / Test Panel", category: "Utilities", description: "Interaction-focused component workflow for checking behavior, events and states.", tags: ["interactions", "testing", "events"] },
  { id: "vuetify-data-table", name: "Data Table / Dense", category: "Data Display", description: "Data-heavy table pattern with sorting, selection, pagination and density controls.", tags: ["table", "data", "pagination"] },
  { id: "vuetify-navigation-drawer", name: "Navigation / Drawer", category: "Navigation", description: "Responsive navigation rail that collapses between desktop and mobile layouts.", tags: ["drawer", "navigation", "responsive"] },
  { id: "vuetify-stepper", name: "Stepper / Workflow", category: "Navigation", description: "Sequential navigation pattern for multi-step workflows and setup journeys.", tags: ["stepper", "workflow", "progress"] },
  { id: "material-dialog", name: "Dialog / Material", category: "Surfaces", description: "Material-style dialog composition for confirmations and focused tasks.", tags: ["material", "dialog", "modal"] },
  { id: "material-autocomplete", name: "Autocomplete / Material", category: "Forms", description: "Searchable suggestion input pattern with labels, selection and keyboard navigation.", tags: ["autocomplete", "forms", "keyboard"] },
  { id: "material-data-grid", name: "Data Grid / Enterprise", category: "Data Display", description: "Rich data grid pattern for sorting, filtering, pinning and dense datasets.", tags: ["data-grid", "table", "enterprise"] },
  { id: "hero-card", name: "Card / Elevated", category: "Cards", description: "Layered card surface with clear hierarchy and interactive states.", tags: ["card", "surface", "interactive"] },
  { id: "hero-modal", name: "Modal / Responsive", category: "Surfaces", description: "Responsive modal pattern designed for polished application flows.", tags: ["modal", "responsive", "a11y"] },
  { id: "hero-select", name: "Select / Polished", category: "Forms", description: "Styled select pattern with clear trigger, menu and selection states.", tags: ["select", "forms", "menu"] },
  { id: "chakra-toast", name: "Toast / Feedback Queue", category: "Feedback", description: "Non-blocking notification pattern for async status and user feedback.", tags: ["toast", "feedback", "async"] },
  { id: "chakra-tabs", name: "Tabs / Accessible", category: "Navigation", description: "Accessible tab pattern for switching related views while preserving hierarchy.", tags: ["tabs", "navigation", "a11y"] },
  { id: "chakra-form", name: "Form / Field Group", category: "Forms", description: "Form composition pattern with labels, help text, validation and layout primitives.", tags: ["form", "validation", "a11y"] },
  { id: "fluent-command", name: "Command / Fluent Palette", category: "Navigation", description: "Command-oriented interaction pattern for productivity-focused applications.", tags: ["command", "keyboard", "productivity"] },
  { id: "fluent-navigation", name: "Navigation / Fluent Rail", category: "Navigation", description: "Structured navigation rail for application shells.", tags: ["navigation", "rail", "responsive"] },
  { id: "fluent-teaching-popover", name: "Teaching / Context Popover", category: "Feedback", description: "Contextual education pattern for introducing product features without blocking the workflow.", tags: ["popover", "onboarding", "education"] },
  { id: "antd-pro-table", name: "Pro Table / Operational", category: "Data Display", description: "Operational table pattern with query forms, actions, sorting and dense data.", tags: ["table", "enterprise", "filters"] },
  { id: "antd-pro-form", name: "Pro Form / Schema Driven", category: "Forms", description: "Higher-level form composition for complex enterprise input workflows.", tags: ["form", "schema", "enterprise"] },
  { id: "mantine-modal", name: "Modal / Mantine", category: "Surfaces", description: "Flexible modal surface with theme-aware spacing and clear action hierarchy.", tags: ["modal", "theme", "actions"] },
  { id: "mantine-navbar", name: "Navigation / App Navbar", category: "Navigation", description: "Application navigation surface with grouped links and responsive collapse.", tags: ["navbar", "navigation", "responsive"] },
  { id: "prime-dialog", name: "Dialog / Prime", category: "Surfaces", description: "Configurable modal workflow with footer actions and responsive behavior.", tags: ["dialog", "modal", "actions"] },
  { id: "prime-datatable", name: "Data Table / Prime", category: "Data Display", description: "Feature-rich table pattern for sorting, filtering, grouping and pagination.", tags: ["datatable", "data", "pagination"] },
  { id: "nuxt-command-palette", name: "Command / Nuxt Palette", category: "Navigation", description: "Command-oriented UI pattern for application workflows.", tags: ["command", "navigation", "search"] },
  { id: "nuxt-calendar", name: "Calendar / Nuxt", category: "Forms", description: "Calendar and date selection surface for product workflows.", tags: ["calendar", "date", "picker"] },
  { id: "element-table", name: "Data Table / Element", category: "Data Display", description: "Dense data table pattern with pagination, filters and operations.", tags: ["table", "data", "filters"] },
  { id: "element-tree", name: "Tree / Element", category: "Data Display", description: "Hierarchical tree control for nested datasets and permissions.", tags: ["tree", "hierarchy", "permissions"] },
  { id: "taiga-field", name: "Field / Taiga", category: "Forms", description: "Structured field composition for validation-heavy interfaces.", tags: ["field", "forms", "validation"] },
  { id: "taiga-dialog", name: "Dialog / Taiga", category: "Surfaces", description: "Dialog pattern optimized for configurable product flows.", tags: ["dialog", "overlay", "workflow"] },
  { id: "primeng-table", name: "Table / PrimeNG", category: "Data Display", description: "Angular data table pattern with enterprise-ready features.", tags: ["table", "data", "enterprise"] },
  { id: "primeng-tree", name: "Tree / PrimeNG", category: "Data Display", description: "Nested tree pattern for hierarchical navigation and data.", tags: ["tree", "hierarchy", "navigation"] },
  { id: "semantic-input", name: "Forms / Semantic Input", category: "Forms", description: "Structured form control pattern with labels, validation and clear input affordances.", tags: ["forms", "validation", "input"] },
  { id: "semantic-message", name: "Feedback / Message", category: "Feedback", description: "Contextual message pattern for status, warnings, errors and confirmation.", tags: ["message", "feedback", "status"] },
  { id: "blueprint-datepicker", name: "Date Picker / Dense", category: "Forms", description: "Desktop-oriented date selection pattern for operational interfaces.", tags: ["date", "picker", "forms"] },
  { id: "blueprint-tree", name: "Tree / Hierarchical", category: "Data Display", description: "Hierarchical navigation pattern for large structured datasets.", tags: ["tree", "hierarchy", "navigation"] },
  { id: "recharts-line", name: "Chart / Time Series", category: "Charts", description: "Composable line chart pattern for trends, deltas and time-series data.", tags: ["chart", "line", "analytics"] },
  { id: "recharts-composed", name: "Chart / Composed", category: "Charts", description: "Mixed visualization pattern combining bars, lines and reference data.", tags: ["chart", "composed", "analytics"] },
  { id: "coss-field", name: "Field / Compound Form", category: "Forms", description: "Compound form field composition with label, description, control and validation parts.", tags: ["field", "forms", "a11y"] },
  { id: "coss-navigation", name: "Navigation / Sidebar", category: "Navigation", description: "Application navigation pattern optimized for dense product shells.", tags: ["sidebar", "navigation", "app-shell"] },
  { id: "base-ui-combobox", name: "Combobox / Accessible", category: "Forms", description: "Autocomplete and selection pattern with keyboard-first interaction.", tags: ["combobox", "keyboard", "a11y"] },
  { id: "base-ui-select", name: "Select / Primitive", category: "Forms", description: "Unstyled select composition with controlled state and accessible interaction.", tags: ["select", "unstyled", "a11y"] },
  { id: "base-ui-toolbar", name: "Toolbar / Composable", category: "Utilities", description: "Keyboard-navigable toolbar for grouped actions and formatting controls.", tags: ["toolbar", "keyboard", "composition"] },
];

export const uiReferenceComponents: VaultComponent[] = catalog.map((component) => ({
  id: `catalog-${component.id}`,
  name: component.name,
  slug: `catalog-${component.id}`,
  description: component.description,
  category: component.category,
  framework: "React",
  language: "tsx",
  version: "v1.0.0",
  userId: "catalog",
  isPublic: true,
  isFavorite: false,
  updatedAt: "2026-08-14T00:00:00.000Z",
  tags: component.tags,
  previewHtml: `<article class="vault-feature-preview"><span>${component.category}</span><strong>${component.name}</strong><small>${component.description}</small></article>`,
  code: `export function ${component.id.replace(/(^|-)([a-z])/g, (_, __, letter: string) => letter.toUpperCase())}() {\n  return (\n    <div className="component-preview">${component.name}</div>\n  );\n}`,
  styles: ".component-preview { border-radius: 16px; border: 1px solid #e4e7ef; background: #fff; padding: 16px; }",
  usageCode: `<${component.id.replace(/(^|-)([a-z])/g, (_, __, letter: string) => letter.toUpperCase())} />`,
  notes: "First-class Component Vault component.",
  tokens: [],
  usage: [],
  props: { variant: "Primary", size: "Medium", state: "Default", iconLeft: false, iconRight: false, fullWidth: false, disabled: false, loading: false },
  collectionIds: ["core-library"],
}));