import type { VaultComponent } from "@/types/vault";

type UIReference = {
  id: string;
  name: string;
  category: VaultComponent["category"];
  description: string;
  tags: string[];
  source: string;
};

const references: UIReference[] = [
  { id: "shadcn-dialog", name: "Dialog / Composable", category: "Surfaces", description: "Composable modal pattern with explicit parts, keyboard behavior and controlled state.", tags: ["shadcn", "dialog", "composition", "a11y"], source: "shadcn-ui/ui" },
  { id: "shadcn-command", name: "Command / Palette", category: "Navigation", description: "Keyboard-first command surface for search, navigation and actions.", tags: ["shadcn", "command", "keyboard", "search"], source: "shadcn-ui/ui" },
  { id: "shadcn-sidebar", name: "Sidebar / Application Shell", category: "Navigation", description: "Collapsible application sidebar pattern with grouped navigation and responsive behavior.", tags: ["shadcn", "sidebar", "navigation", "app-shell"], source: "shadcn-ui/ui" },
  { id: "shadcn-data-table", name: "Data Table / Composable", category: "Data Display", description: "Composable table pattern for sorting, filtering, selection and pagination.", tags: ["shadcn", "table", "data", "composition"], source: "shadcn-ui/ui" },
  { id: "shadcn-sheet", name: "Sheet / Side Panel", category: "Surfaces", description: "Responsive side panel pattern for secondary workflows and inspectors.", tags: ["shadcn", "sheet", "drawer", "responsive"], source: "shadcn-ui/ui" },
  { id: "radix-popover", name: "Popover / Primitive", category: "Surfaces", description: "Anchored overlay primitive with focus management and collision-aware positioning.", tags: ["radix", "popover", "overlay", "a11y"], source: "radix-ui/primitives" },
  { id: "radix-tooltip", name: "Tooltip / Primitive", category: "Feedback", description: "Accessible contextual hint with trigger, delay and keyboard semantics.", tags: ["radix", "tooltip", "a11y", "interaction"], source: "radix-ui/primitives" },
  { id: "radix-dropdown", name: "Dropdown / Menu", category: "Navigation", description: "Keyboard-accessible action menu with roving focus and nested options.", tags: ["radix", "menu", "keyboard", "a11y"], source: "radix-ui/primitives" },
  { id: "storybook-controls", name: "Controls / Component Playground", category: "Utilities", description: "Interactive control surface for changing component props and viewing states.", tags: ["storybook", "controls", "props", "testing"], source: "storybookjs/storybook" },
  { id: "storybook-states", name: "States / Visual Review", category: "Data Display", description: "Structured preview of component states for review and regression checks.", tags: ["storybook", "states", "visual", "testing"], source: "storybookjs/storybook" },
  { id: "storybook-interactions", name: "Interactions / Test Panel", category: "Utilities", description: "Interaction-focused component workflow for checking behavior, events and states.", tags: ["storybook", "interactions", "testing", "events"], source: "storybookjs/storybook" },
  { id: "vuetify-data-table", name: "Data Table / Dense", category: "Data Display", description: "Data-heavy table pattern with sorting, selection, pagination and density controls.", tags: ["vuetify", "table", "data", "pagination"], source: "vuetifyjs/vuetify" },
  { id: "vuetify-navigation-drawer", name: "Navigation / Drawer", category: "Navigation", description: "Responsive navigation rail that collapses between desktop and mobile layouts.", tags: ["vuetify", "drawer", "navigation", "responsive"], source: "vuetifyjs/vuetify" },
  { id: "vuetify-stepper", name: "Stepper / Workflow", category: "Navigation", description: "Sequential navigation pattern for multi-step workflows and setup journeys.", tags: ["vuetify", "stepper", "workflow", "progress"], source: "vuetifyjs/vuetify" },
  { id: "material-dialog", name: "Dialog / Material", category: "Surfaces", description: "Material-style dialog composition for confirmations and focused tasks.", tags: ["mui", "material", "dialog", "modal"], source: "mui/material-ui" },
  { id: "material-autocomplete", name: "Autocomplete / Material", category: "Forms", description: "Searchable suggestion input pattern with labels, selection and keyboard navigation.", tags: ["mui", "material", "autocomplete", "forms"], source: "mui/material-ui" },
  { id: "material-data-grid", name: "Data Grid / Enterprise", category: "Data Display", description: "Rich data grid pattern for sorting, filtering, pinning and dense datasets.", tags: ["mui", "data-grid", "table", "enterprise"], source: "mui/material-ui" },
  { id: "hero-card", name: "Card / Elevated", category: "Cards", description: "Layered card surface with clear hierarchy and interactive states.", tags: ["heroui", "card", "surface", "interactive"], source: "heroui-inc/heroui" },
  { id: "hero-modal", name: "Modal / Responsive", category: "Surfaces", description: "Responsive modal pattern designed for polished application flows.", tags: ["heroui", "modal", "responsive", "a11y"], source: "heroui-inc/heroui" },
  { id: "hero-select", name: "Select / Polished", category: "Forms", description: "Styled select pattern with clear trigger, menu and selection states.", tags: ["heroui", "select", "forms", "menu"], source: "heroui-inc/heroui" },
  { id: "chakra-toast", name: "Toast / Feedback Queue", category: "Feedback", description: "Non-blocking notification pattern for async status and user feedback.", tags: ["chakra", "toast", "feedback", "async"], source: "chakra-ui/chakra-ui" },
  { id: "chakra-tabs", name: "Tabs / Accessible", category: "Navigation", description: "Accessible tab pattern for switching related views while preserving hierarchy.", tags: ["chakra", "tabs", "navigation", "a11y"], source: "chakra-ui/chakra-ui" },
  { id: "chakra-form", name: "Form / Field Group", category: "Forms", description: "Form composition pattern with labels, help text, validation and layout primitives.", tags: ["chakra", "form", "validation", "a11y"], source: "chakra-ui/chakra-ui" },
  { id: "fluent-command", name: "Command / Fluent Palette", category: "Navigation", description: "Command-oriented interaction pattern for productivity-focused applications.", tags: ["fluent", "command", "keyboard", "productivity"], source: "microsoft/fluentui" },
  { id: "fluent-navigation", name: "Navigation / Fluent Rail", category: "Navigation", description: "Structured navigation rail for Microsoft-style application shells.", tags: ["fluent", "navigation", "rail", "responsive"], source: "microsoft/fluentui" },
  { id: "fluent-teaching-popover", name: "Teaching / Context Popover", category: "Feedback", description: "Contextual education pattern for introducing product features without blocking the workflow.", tags: ["fluent", "popover", "onboarding", "education"], source: "microsoft/fluentui" },
  { id: "antd-pro-table", name: "Pro Table / Operational", category: "Data Display", description: "Operational table pattern with query forms, actions, sorting and dense data.", tags: ["antd", "pro-components", "table", "enterprise"], source: "ant-design/pro-components" },
  { id: "antd-pro-form", name: "Pro Form / Schema Driven", category: "Forms", description: "Higher-level form composition for complex enterprise input workflows.", tags: ["antd", "pro-components", "form", "schema"], source: "ant-design/pro-components" },
  { id: "mantine-modal", name: "Modal / Mantine", category: "Surfaces", description: "Flexible modal surface with theme-aware spacing and clear action hierarchy.", tags: ["mantine", "modal", "theme", "actions"], source: "mantinedev/ui.mantine.dev" },
  { id: "mantine-navbar", name: "Navigation / App Navbar", category: "Navigation", description: "Application navigation surface with grouped links and responsive collapse.", tags: ["mantine", "navbar", "navigation", "responsive"], source: "mantinedev/ui.mantine.dev" },
  { id: "prime-dialog", name: "Dialog / Prime", category: "Surfaces", description: "Configurable modal workflow with footer actions and responsive behavior.", tags: ["primevue", "dialog", "modal", "vue"], source: "primefaces/primevue" },
  { id: "prime-datatable", name: "Data Table / Prime", category: "Data Display", description: "Feature-rich table pattern for sorting, filtering, grouping and pagination.", tags: ["primevue", "datatable", "data", "vue"], source: "primefaces/primevue" },
  { id: "nuxt-command-palette", name: "Command / Nuxt Palette", category: "Navigation", description: "Command-oriented UI pattern adapted for Nuxt application workflows.", tags: ["nuxt-ui", "command", "navigation", "vue"], source: "nuxt/ui" },
  { id: "nuxt-calendar", name: "Calendar / Nuxt", category: "Forms", description: "Calendar and date selection surface for product workflows.", tags: ["nuxt-ui", "calendar", "date", "vue"], source: "nuxt/ui" },
  { id: "element-table", name: "Data Table / Element", category: "Data Display", description: "Dense data table pattern with pagination, filters and operations.", tags: ["element", "table", "data", "vue"], source: "ElemeFE/element" },
  { id: "element-tree", name: "Tree / Element", category: "Data Display", description: "Hierarchical tree control for nested datasets and permissions.", tags: ["element", "tree", "hierarchy", "vue"], source: "ElemeFE/element" },
  { id: "taiga-field", name: "Field / Taiga", category: "Forms", description: "Structured field composition for validation-heavy interfaces.", tags: ["taiga", "field", "forms", "angular"], source: "taiga-family/taiga-ui" },
  { id: "taiga-dialog", name: "Dialog / Taiga", category: "Surfaces", description: "Dialog pattern optimized for configurable product flows.", tags: ["taiga", "dialog", "overlay", "angular"], source: "taiga-family/taiga-ui" },
  { id: "primeng-table", name: "Table / PrimeNG", category: "Data Display", description: "Angular data table pattern with enterprise-ready features.", tags: ["primeng", "table", "data", "angular"], source: "primefaces/primeng" },
  { id: "primeng-tree", name: "Tree / PrimeNG", category: "Data Display", description: "Nested tree pattern for hierarchical navigation and data.", tags: ["primeng", "tree", "hierarchy", "angular"], source: "primefaces/primeng" },
  { id: "semantic-input", name: "Forms / Semantic Input", category: "Forms", description: "Structured form control pattern with labels, validation and clear input affordances.", tags: ["semantic-ui", "forms", "validation", "input"], source: "Semantic-Org/Semantic-UI" },
  { id: "semantic-message", name: "Feedback / Message", category: "Feedback", description: "Contextual message pattern for status, warnings, errors and confirmation.", tags: ["semantic-ui", "message", "feedback", "status"], source: "Semantic-Org/Semantic-UI" },
  { id: "blueprint-datepicker", name: "Date Picker / Dense", category: "Forms", description: "Desktop-oriented date selection pattern for operational interfaces.", tags: ["blueprint", "date", "picker", "forms"], source: "palantir/blueprint" },
  { id: "blueprint-tree", name: "Tree / Hierarchical", category: "Data Display", description: "Hierarchical navigation pattern for large structured datasets.", tags: ["blueprint", "tree", "hierarchy", "navigation"], source: "palantir/blueprint" },
  { id: "recharts-line", name: "Chart / Time Series", category: "Charts", description: "Composable line chart pattern for trends, deltas and time-series data.", tags: ["recharts", "chart", "line", "analytics"], source: "recharts/recharts" },
  { id: "recharts-composed", name: "Chart / Composed", category: "Charts", description: "Mixed visualization pattern combining bars, lines and reference data.", tags: ["recharts", "chart", "composed", "analytics"], source: "recharts/recharts" },
  { id: "coss-field", name: "Field / Compound Form", category: "Forms", description: "Compound form field composition with label, description, control and validation parts.", tags: ["coss", "field", "forms", "a11y"], source: "cosscom/coss" },
  { id: "coss-navigation", name: "Navigation / Sidebar", category: "Navigation", description: "Application navigation pattern optimized for dense product shells.", tags: ["coss", "sidebar", "navigation", "app-shell"], source: "cosscom/coss" },
  { id: "base-ui-combobox", name: "Combobox / Accessible", category: "Forms", description: "Autocomplete and selection pattern with keyboard-first interaction.", tags: ["base-ui", "combobox", "keyboard", "a11y"], source: "mui/base-ui" },
  { id: "base-ui-select", name: "Select / Primitive", category: "Forms", description: "Unstyled select composition with controlled state and accessible interaction.", tags: ["base-ui", "select", "unstyled", "a11y"], source: "mui/base-ui" },
  { id: "base-ui-toolbar", name: "Toolbar / Composable", category: "Utilities", description: "Keyboard-navigable toolbar for grouped actions and formatting controls.", tags: ["base-ui", "toolbar", "keyboard", "composition"], source: "mui/base-ui" },
];

export const uiReferenceComponents: VaultComponent[] = references.map((reference) => ({
  id: `reference-${reference.id}`,
  name: reference.name,
  slug: `reference-${reference.id}`,
  description: reference.description,
  category: reference.category,
  framework: "React",
  language: "tsx",
  version: "reference",
  userId: "reference-catalog",
  isPublic: true,
  isFavorite: false,
  updatedAt: "2026-08-14T00:00:00.000Z",
  tags: [...reference.tags, "ui-reference"],
  previewHtml: `<article class="vault-feature-preview"><span>${reference.source}</span><strong>${reference.name}</strong><small>${reference.description}</small></article>`,
  code: `// Original Component Vault reference implementation\n// Source pattern: ${reference.source}\n\nexport function ${reference.id.replace(/(^|-)([a-z])/g, (_, __, letter: string) => letter.toUpperCase())}() {\n  return null;\n}`,
  styles: ".vault-reference { border-radius: 16px; border: 1px solid #e4e7ef; background: #fff; }",
  usageCode: `<${reference.id.replace(/(^|-)([a-z])/g, (_, __, letter: string) => letter.toUpperCase())} />`,
  notes: `Reference pattern inspired by ${reference.source}. This catalog stores an original Component Vault implementation concept, not copied source code.`,
  tokens: [],
  usage: [],
  props: { variant: "Primary", size: "Medium", state: "Default", iconLeft: false, iconRight: false, fullWidth: false, disabled: false, loading: false },
  collectionIds: ["ui-references"],
}));
