#!/usr/bin/env node
import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync, statSync, writeFileSync, mkdirSync } from "node:fs";
import { extname, join, relative, resolve, sep, dirname } from "node:path";
import process from "node:process";
import ts from "typescript";
import YAML from "yaml";

const VERSION = "0.3.2";
const DEFAULT_CONFIG = "component-vault.yaml";
const DEFAULT_BASELINE = "component-vault.baseline.json";
const RULES = { CV001:"Direct component import", CV002:"Forbidden variant override", CV003:"Raw semantic element", CV004:"Repeated static style", CV005:"Forbidden pattern" };
const posix = (v) => v.split(sep).join("/");
const hash = (v) => createHash("sha1").update(v).digest("hex").slice(0,16);

function args(argv) {
  const command = argv[0] ?? "scan", options = {};
  for (let i=1;i<argv.length;i++) if (argv[i].startsWith("--")) { const k=argv[i].slice(2), n=argv[i+1]; options[k]=n && !n.startsWith("--") ? n : true; if(options[k]!==true)i++; }
  return {command,options};
}
function config(root,path=DEFAULT_CONFIG) {
  const p=resolve(root,path); if(!existsSync(p)) throw new Error(`Configuration not found: ${path}`);
  const c=YAML.parse(readFileSync(p,"utf8")); if(!c || c.version!==1) throw new Error("component-vault.yaml must use version: 1");
  c.scan??={}; c.scan.include??=["src"]; c.scan.exclude??=["node_modules",".next",".git","dist","build","coverage"]; c.scan.extensions??=[".ts",".tsx",".js",".jsx"];
  c.duplicates??={enabled:true,minOccurrences:5,minTokens:5}; c.components??={}; c.rules??={}; c.rules.forbiddenPatterns??=[]; c.rules.fixes??={}; return c;
}
function wildcard(p){const e=String(p).replace(/[.+^${}()|[\]\\]/g,"\\$&").replace(/\*\*/g,"__DS__").replace(/\*/g,"[^/]*").replace(/__DS__/g,".*");return new RegExp(`^${e}$`);}
function matches(file,p){const n=posix(String(p)).replace(/^\.\//,"");return n.includes("*")?wildcard(n).test(file):file===n||file.startsWith(`${n}/`);}
function files(root,c){const out=[],ext=new Set(c.scan.extensions.map(String)),ex=c.scan.exclude.map(String);function visit(p){const r=posix(relative(root,p));if(r&&ex.some(x=>matches(r,x)))return;const s=statSync(p);if(s.isDirectory()){for(const x of readdirSync(p))visit(join(p,x));}else if(ext.has(extname(p)))out.push(r);}for(const x of c.scan.include){const p=resolve(root,String(x));if(existsSync(p))visit(p);}return out.sort();}
function kind(f){return f.endsWith(".tsx")?ts.ScriptKind.TSX:f.endsWith(".jsx")?ts.ScriptKind.JSX:f.endsWith(".js")?ts.ScriptKind.JS:ts.ScriptKind.TS;}
function ignored(sf,start,rule){const line=sf.getLineAndCharacterOfPosition(start).line,ls=sf.text.split(/\r?\n/);return ls.slice(Math.max(0,line-1),line+1).join("\n").includes(`component-vault-ignore ${rule}`)||ls.slice(Math.max(0,line-1),line+1).join("\n").includes("component-vault-ignore all");}
function violation(o){const l=o.sf.getLineAndCharacterOfPosition(o.start);return {rule:o.rule,title:RULES[o.rule]??o.rule,severity:o.severity??"error",component:o.component,file:o.file,line:l.line+1,column:l.character+1,snippet:String(o.snippet).replace(/\s+/g," ").trim().slice(0,280),message:o.message,suggestion:o.suggestion,metadata:o.metadata??{},fingerprint:hash([o.rule,o.component??"",o.file,o.snippet].join("|"))};}
function allowed(file,r){return [r.source,...(r.allowedImportFiles??[])].filter(Boolean).some(p=>matches(file,p));}
function hasImport(ic,name){if(!ic)return false;if(ic.name?.text===name)return true;const b=ic.namedBindings;return !!(b&&ts.isNamedImports(b)&&b.elements.some(e=>(e.propertyName?.text??e.name.text)===name));}
function staticClass(a){if(!a?.initializer)return null;if(ts.isStringLiteral(a.initializer))return a.initializer.text;if(ts.isJsxExpression(a.initializer)&&a.initializer.expression&&(ts.isStringLiteral(a.initializer.expression)||ts.isNoSubstitutionTemplateLiteral(a.initializer.expression)))return a.initializer.expression.text;return null;}
function scan(root,c){const dup=new Map(),out=[];for(const file of files(root,c)){const text=readFileSync(resolve(root,file),"utf8"),sf=ts.createSourceFile(file,text,ts.ScriptTarget.Latest,true,kind(file));function visit(n){if(ts.isImportDeclaration(n)&&ts.isStringLiteral(n.moduleSpecifier)){const mod=n.moduleSpecifier.text;for(const [name,r] of Object.entries(c.components)){const bad=(r.forbiddenImports??[]).some(x=>mod===String(x)||mod.startsWith(`${x}/`));if(!allowed(file,r)&&bad&&hasImport(n.importClause,name)&&!ignored(sf,n.getStart(sf),"CV001"))out.push(violation({rule:"CV001",component:name,file,sf,start:n.getStart(sf),snippet:n.getText(sf),message:`Direct import of ${name} from ${mod} is forbidden.`,suggestion:`Import ${name} from ${r.source}.`,metadata:{moduleName:mod}}));}}
if(ts.isJsxOpeningElement(n)||ts.isJsxSelfClosingElement(n)){const tag=n.tagName.getText(sf),a=n.attributes.properties.find(x=>ts.isJsxAttribute(x)&&x.name.text==="className"),cl=a&&staticClass(a);if(cl){const t=cl.trim().split(/\s+/).filter(Boolean);if(t.length>=Number(c.duplicates.minTokens??5)){const key=[...t].sort().join(" "),list=dup.get(key)??[];list.push({file,sf,start:a.getStart(sf),snippet:a.getText(sf)});dup.set(key,list);}}
for(const [name,r] of Object.entries(c.components)){if(allowed(file,r))continue;const raw=r.rawElements??{};if(Object.hasOwn(raw,tag)&&!ignored(sf,n.getStart(sf),"CV003")){const v=raw[tag];out.push(violation({rule:"CV003",component:name,file,sf,start:n.getStart(sf),snippet:n.getText(sf),message:`Raw <${tag}> detected in governed JSX.`,suggestion:`Use <${name}.${v}> instead.`,metadata:{element:tag,variant:v}}));}if(tag.startsWith(`${name}.`)){const v=tag.slice(name.length+1),props=new Set((r.forbiddenProps??[]).map(String));for(const a of n.attributes.properties)if(ts.isJsxAttribute(a)&&props.has(a.name.text)&&!ignored(sf,a.getStart(sf),"CV002"))out.push(violation({rule:"CV002",component:name,file,sf,start:a.getStart(sf),snippet:a.getText(sf),message:`${name}.${v} overrides protected prop ${a.name.text}.`,suggestion:`Use the documented ${name}.${v} style or create a governed variant.`,metadata:{variant:v,prop:a.name.text}}));}}}ts.forEachChild(n,visit);}visit(sf);}
if(c.duplicates.enabled)for(const [classes,list] of dup)if(list.length>=Number(c.duplicates.minOccurrences??5))for(const x of list)out.push(violation({rule:"CV004",file:x.file,sf:x.sf,start:x.start,snippet:x.snippet,message:`The same static className combination appears ${list.length} times.`,suggestion:"Consider extracting a governed component or reusable style token.",metadata:{occurrences:list.length,classes}}));
return out;}
function changed(root,base){if(!base)return null;try{return new Set(execFileSync("git",["diff","--name-only",`${base}...HEAD"],{cwd:root,encoding:"utf8"}).split(/\r?\n/).filter(Boolean).map(posix));}catch{return new Set();}}
function blocking(root,vs,c,base){const ch=changed(root,base);if(!ch)return vs;return vs.filter(v=>{const strategy=c.components[v.component]?.strategy??"touched";return strategy!=="touched"||ch.has(v.file);});}
function loadBaseline(root,path=DEFAULT_BASELINE){const p=resolve(root,path);if(!existsSync(p))return{version:2,fingerprints:[],violations:[]};return JSON.parse(readFileSync(p,"utf8"));}
function doBaseline(root,c,path){const vs=scan(root,c),p=resolve(root,path);mkdirSync(dirname(p),{recursive:true});writeFileSync(p,JSON.stringify({version:2,generatedAt:new Date().toISOString(),fingerprints:vs.map(v=>v.fingerprint),violations:vs},null,2)+"\n");console.log(`Component Vault: baseline captured ${vs.length} violation(s).`);}
function doReport(root,c,path,out,base){const vs=scan(root,c),b=loadBaseline(root,path),bs=new Set(b.fingerprints??[]),cs=new Set(vs.map(v=>v.fingerprint)),legacy=vs.filter(v=>bs.has(v.fingerprint)),fresh=vs.filter(v=>!bs.has(v.fingerprint)),resolved=(b.fingerprints??[]).filter(x=>!cs.has(x)).length,block=blocking(root,fresh,c,base),total=(b.fingerprints??[]).length,p={engine:"typescript-ast",generatedAt:new Date().toISOString(),violations:vs,summary:{migrationProgress:total?Math.round(resolved/total*100):(fresh.length?0:100),legacy:legacy.length,resolved,new:fresh.length,blocking:block.length,filesScanned:files(root,c).length}};const dest=resolve(root,out);mkdirSync(dirname(dest),{recursive:true});writeFileSync(dest,JSON.stringify(p,null,2)+"\n");console.log(`Component Vault: report generated with ${block.length} blocking violation(s).`);return p;}
function print(vs){if(!vs.length){console.log("Component Vault: no violations found.");return;}for(const v of vs){console.log(`\n[${v.rule}] ${v.title}`);console.log(`${v.file}:${v.line}:${v.column}`);console.log(`  ${v.message}`);if(v.snippet)console.log(`  ${v.snippet}`);if(v.suggestion)console.log(`  → ${v.suggestion}`);}console.log(`\nComponent Vault: ${vs.length} violation(s).`);}
function main(){const root=process.cwd(),{command,options}=args(process.argv.slice(2));try{if(command==="version"||command==="--version")return console.log(`component-vault ${VERSION}`);const c=config(root,String(options.config??DEFAULT_CONFIG));if(command==="scan"){print(scan(root,c));process.exitCode=0;return;}if(command==="check"){const b=blocking(root,scan(root,c),c,typeof options.base==="string"?options.base:undefined);print(b);console.log(`\n${b.length} blocking violation${b.length===1?"":"s"}.`);process.exitCode=b.length?1:0;return;}if(command==="baseline"){doBaseline(root,c,String(options.baseline??DEFAULT_BASELINE));return;}if(command==="report"){doReport(root,c,String(options.baseline??DEFAULT_BASELINE),String(options.output??"public/component-vault-report.json"),typeof options.base==="string"?options.base:undefined);return;}if(command==="fix"){process.exitCode=0;return;}throw new Error(`Unknown command: ${command}`);}catch(e){console.error(`Component Vault error: ${e instanceof Error?e.message:String(e)}`);process.exitCode=1;}}main();
